# Generated by Django 4.1.4 on 2022-12-19 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.URLField()),
            ],
            options={
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='PaymentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paymentDate', models.DateField()),
                ('expirationDate', models.DateField()),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PaymentUser',
            },
        ),
        migrations.CreateModel(
            name='ExpiredPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_fee_amount', models.FloatField()),
                ('pay_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.paymentuser')),
            ],
            options={
                'db_table': 'ExpiredPayment',
            },
        ),
    ]
